// Generated by: supabase gen types typescript --project-id <project-id>
// Run after Phase 1 migrations: npx supabase gen types typescript --local > types/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      urgency_level: "low" | "medium" | "high" | "urgent";
      project_status: "active" | "on_hold" | "completed" | "archived";
      task_status: "todo" | "in_progress" | "done";
      notification_type:
        | "task_assigned"
        | "task_due_soon"
        | "task_status_changed"
        | "project_due_soon"
        | "mention";
    };
  };
};

export type UrgencyLevel = Database["public"]["Enums"]["urgency_level"];
export type ProjectStatus = Database["public"]["Enums"]["project_status"];
export type TaskStatus = Database["public"]["Enums"]["task_status"];
export type NotificationType = Database["public"]["Enums"]["notification_type"];
